export const projects = [
  {
    title: "Termoland",
    image: "/img/projects/termoland-logo.png",
    link: "https://termoland.ru/",
    description: "Федеральная сеть Городских курортов с фитнесом, предоставляющих уникальную возможность совмещать урбанистический стиль жизни с роскошью курортного отдыха.",
    features: ["Bitrix"],
  },
  {
    title: "MRC-club",
    image: "/img/projects/mrc-logo.png",
    link: "https://mrc-club.ru/",
    description: "MRC-club — это инновационная экосистема, созданная с учетом потребностей PR-специалистов, опытных спикеров и представителей СМИ.",
    features: ["Joomla*", "React"],
    note: "*Ранее сайт был на CMS Joomla",
  },
  {
    title: "Allure Lodge",
    image: "/img/projects/allure-logo.png",
    link: "https://allure-arkhyz.ru/",
    description: "Allure Lodge – место, где первозданная природа гор встречается с современным кавказским гостеприимством, создавая уникальное пространство для незабываемого семейного отдыха.",
    features: ["Bitrix"],
  },
  {
    title: "Гранд-Мех",
    image: "/img/projects/grand-logo.png",
    link: "https://grand-mech.ru/",
    description: "Услуги по мехобработке, металлообработке на чпу станках и универсальных станках изделий из стали, алюминия, пластмассы под заказ.",
    features: ["Joomla"],
  },
  {
    title: "Бельтона",
    image: "/img/projects/beltona-logo.png",
    link: "https://beltona.ru/",
    description: "«Beltona» — производитель современной и стильной брендированной упаковки для различных отраслей.",
    features: ["Joomla"],
  },
  {
    title: "Тосол Синтез",
    image: "/img/projects/tara-logo.png",
    link: "https://tara-ts.ru/",
    description: "Завод пластиковой тары в Москве — изготовление и продажа тары оптом: канистры, емкости, пищевая тара, тара для бытовой химии и косметики.",
    features: ["Evoluton"],
  },
  {
    title: "Motoxmoto",
    image: "/img/projects/motoxmoto-logo.png",
    link: "https://motoxmoto.ru/",
    description: "Магазин мотоэкипировки в Москве. Мотоэкипировка, произведенную по заказу и от сторонних производителей.",
    features: ["Wordpress"],
  },
  {
    title: "А-Текстиль",
    image: "/img/projects/atextil-logo.png",
    link: "https://atextil.ru/",
    description: "«А-Текстиль» — широкий ассортимент тканей, материалов для шитья и швейной фурнитуры.",
    features: ["Bitrix"],
  },
  {
    title: "Феномен",
    image: "/img/projects/fenomen-logo.png",
    link: "https://fenomen-chess.ru/",
    description: "Шахматная школа, основанная международным мастером Яном Джумагалиевым.",
    features: ["Wordpress"],
  },
];